name = "Exercism"
uuid = "5bba1ac5-e1f5-41ac-a027-d87008a33ee3"
version = "0.1.0"
authors = ["Avilay Parekh <avilay@gmail.com>"]

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
